//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrainCard.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrainCard.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Back に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BackButtonContent {
            get {
                return ResourceManager.GetString("BackButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blur Radius に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BlurRadiusSliderHeader {
            get {
                return ResourceManager.GetString("BlurRadiusSliderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ClearAll に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClearButtonContent {
            get {
                return ResourceManager.GetString("ClearButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Canvas Color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColorPickerButtonHeader {
            get {
                return ResourceManager.GetString("ColorPickerButtonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenuEditHeader {
            get {
                return ResourceManager.GetString("ContextMenuEditHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Debug Mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DebugModeSwitchHeader {
            get {
                return ResourceManager.GetString("DebugModeSwitchHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OFF に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DebugModeSwitchOffContent {
            get {
                return ResourceManager.GetString("DebugModeSwitchOffContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ON に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DebugModeSwitchOnContent {
            get {
                return ResourceManager.GetString("DebugModeSwitchOnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Direction に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DirectionSliderHeader {
            get {
                return ResourceManager.GetString("DirectionSliderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Front に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FrontButtonContent {
            get {
                return ResourceManager.GetString("FrontButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Writing Canvas Window に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InputWindowToggleSwitchHeader {
            get {
                return ResourceManager.GetString("InputWindowToggleSwitchHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InputWindowToggleSwitchOffContent {
            get {
                return ResourceManager.GetString("InputWindowToggleSwitchOffContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Visible に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InputWindowToggleSwitchOnContent {
            get {
                return ResourceManager.GetString("InputWindowToggleSwitchOnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LanguageSelectorHeader {
            get {
                return ResourceManager.GetString("LanguageSelectorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoadButtonContent {
            get {
                return ResourceManager.GetString("LoadButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Opacity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpacitySliderHeader {
            get {
                return ResourceManager.GetString("OpacitySliderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Over Write に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OverWriteMenuContent {
            get {
                return ResourceManager.GetString("OverWriteMenuContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pin に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PinButtonContent {
            get {
                return ResourceManager.GetString("PinButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save New に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveAsMenuContent {
            get {
                return ResourceManager.GetString("SaveAsMenuContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveButtonContent {
            get {
                return ResourceManager.GetString("SaveButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zoom for Scale に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ScaleSliderHeader {
            get {
                return ResourceManager.GetString("ScaleSliderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ShadowColor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShadowColorPickerButtonHeader {
            get {
                return ResourceManager.GetString("ShadowColorPickerButtonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shadow Depth に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShadowDepthSliderHeader {
            get {
                return ResourceManager.GetString("ShadowDepthSliderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Selected Card Style に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShadowToggleSwitchHeader {
            get {
                return ResourceManager.GetString("ShadowToggleSwitchHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Simple に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShadowToggleSwitchOffContent {
            get {
                return ResourceManager.GetString("ShadowToggleSwitchOffContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Color Shadow に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShadowToggleSwitchOnContent {
            get {
                return ResourceManager.GetString("ShadowToggleSwitchOnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Theme に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ThemeToggleSwitchHeader {
            get {
                return ResourceManager.GetString("ThemeToggleSwitchHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Light に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ThemeToggleSwitchOffContent {
            get {
                return ResourceManager.GetString("ThemeToggleSwitchOffContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dark に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ThemeToggleSwitchOnContent {
            get {
                return ResourceManager.GetString("ThemeToggleSwitchOnContent", resourceCulture);
            }
        }
    }
}
